### ISSUE TITLE
内测问题汇总

### ISSUE THREAD

**Issue by Davidliu027** [youwallet/wallet#47]
**问题汇总如下，H高优先级，M中优先 级，L低优先级**

- [x] H 首页-下拉刷新；
- [x] M 首页-钱包名称旁加二维码，点击进入收款页面；
- [x] H 钱包-导出私钥；
- [x] M 转帐-先隐藏转帐模式手续费的选择，慢中快速，手续费改成“矿工费用”
- [ ] Q gaslimit计算资源，gasprice单价，矿工费=花费gas数量Xgasprice，@用心；
- [x] H 兑换-TOKEN资产根据钱包/网络切换刷新；
- [ ] H 兑换-切换TOKEN组合，刷新交易历史和深度；
- [ ] H 兑换-交易深度没有显示；
- [x] M 兑换-切换买入卖出时页面字体和背景都需要变化；
- [x] H 兑换-买单卖单没有自动撮合；
- [x] H 兑换-页面；
- [ ] 兑换历史记录是否可以从链上获取，@用心；

![image](https://user-images.githubusercontent.com/19386653/71758854-e0a95580-2edf-11ea-938f-23c1644b81a1.png)
![image](https://user-images.githubusercontent.com/19386653/71758877-059dc880-2ee0-11ea-9434-ad98adc44303.png)

**Comment by zhaobinglong** [comment]
![image](https://user-images.githubusercontent.com/8922614/71431911-6d018e80-2710-11ea-9cdc-087cb40ac59a.png)
买入数量的输入格式要求
买个价格的输入格式要求

**Comment by zhaobinglong** [comment]
推测出一个问题：如果当前已经有交易在打包，似乎就不能继续发起交易了
![image](https://user-images.githubusercontent.com/8922614/71500685-0a8bc800-28a1-11ea-941d-07ff24a26963.png)

**Comment by zhaobinglong** [comment]
关于指纹识别：

调用硬件设备的指纹识别，设备只会返回一个true或者false，开发者通过true和false判断指纹识别是否通过，其他信息都没有，所以根据目前的结果，不能实现拿用户的指纹信息来加密私钥，还是需要通过用户设置密码来加密私钥

![image](https://user-images.githubusercontent.com/8922614/71507729-75003080-28c0-11ea-98e8-def51cf46861.png)

**Comment by zhaobinglong** [comment]
获取当前交易列表接口需要明确：
![image](https://user-images.githubusercontent.com/8922614/71510797-12606200-28cb-11ea-9458-3f767bd91757.png)

**Comment by zhaobinglong** [comment]
点击买入或者卖出，是否需要弹出指纹识别确认是否该设置的用户在操作？
![image](https://user-images.githubusercontent.com/8922614/71513612-0af28600-28d6-11ea-85b0-617faeb2e1ce.png)

**Comment by zhaobinglong** [comment]
客户端这里的shou'xu手续费显示多少
![image](https://user-images.githubusercontent.com/8922614/71513663-3b3a2480-28d6-11ea-9aac-1800089d4046.png)

**Comment by zhaobinglong** [comment]
这里用户转账成功后，客户端是否需要本地保存转账记录
![image](https://user-images.githubusercontent.com/8922614/71519546-f2dd2f80-28f2-11ea-933d-35cdd94e996d.png)

**Comment by zhaobinglong** [comment]
使用私钥导入钱包，则无法在钱包设置页面导出助记词

点击导出助记词后：
点击导出私钥后：

![image](https://user-images.githubusercontent.com/8922614/71544995-c42d8a80-29c0-11ea-90c7-356afca09af1.png)

**Comment by zhaobinglong** [comment]
明确下面这个页面的交互入口：
![image](https://user-images.githubusercontent.com/8922614/71545038-46b64a00-29c1-11ea-8811-0f3f74f5be96.png)

**Comment by zhaobinglong** [comment]
沟通一下ENS合约的理解
![image](https://user-images.githubusercontent.com/8922614/71545090-e542ab00-29c1-11ea-9bcf-1c602dc6435d.png)

**Comment by zhaobinglong** [comment]
```
/* 获取订单信息
 * bq_hash: base-token/quote-token 哈希值
 * od_hash: 订单哈希值
 * is_sell: true 为卖单，false为买单
 *
 * 返回值：
 * 订单信息 QueueElem(参考该结构体)
 * */
function getOrderInfo(bytes32 bq_hash, bytes32 od_hash, bool is_sell);

```

**Comment by Davidliu027** [comment]
首页下拉刷新；
首页钱包名称旁加二维码，点击进入收款页面；
TOKEN资产根据钱包/网络切换刷新；
导出私钥。

**Comment by zhaobinglong** [comment]
隐藏转账模式的自定义
![image](https://user-images.githubusercontent.com/8922614/71774047-cab09900-2fa2-11ea-89ed-360b4aea0c68.png)

**Comment by Davidliu027** [comment]
卖单一直无法在深度交易列表显示，买单有的可以显示有的一直没有显示出来。
另外还有5个问题如下。

![image](https://user-images.githubusercontent.com/19386653/75092906-a3944200-55b7-11ea-80d1-dd5847da216c.png)
![image](https://user-images.githubusercontent.com/19386653/75092890-7e073880-55b7-11ea-80fe-f6534d6343d4.png)
![image](https://user-images.githubusercontent.com/19386653/75092897-90817200-55b7-11ea-9394-f0a326123631.png)
![image](https://user-images.githubusercontent.com/19386653/75092898-99724380-55b7-11ea-98fb-0075f8a3c7ee.png)
![image](https://user-images.githubusercontent.com/19386653/75092900-9d9e6100-55b7-11ea-9d2b-baa3c0324597.png)
