### ISSUE TITLE
根据Hash查询订单在各种情况下的返回json

### ISSUE THREAD

**Issue by zhaobinglong** [youwallet/wallet#79]
一个成功的订单：0x82455ac541bac4f69294ca6329ed04a4513d86038e020a89fb011ba5424cf0c2
![image](https://user-images.githubusercontent.com/8922614/76191056-6cf63280-6219-11ea-9b2d-bbb2d286cd7a.png)

**Comment by zhaobinglong** [comment]
一个失败的订单：0xa03869701750008d86003f2dcc27a503f3888c99acef53c72b7e0bb22136cdeb
![image](https://user-images.githubusercontent.com/8922614/76191945-75e80380-621b-11ea-9dac-c6b81bace070.png)

**Comment by hnuyx** [comment]
应该有个getTransactionReceipt的接口的，python上对应的接口如下。
![image](https://user-images.githubusercontent.com/975736/76422621-7b427b00-63e0-11ea-9180-dde4c51c5e23.png)
